//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mirrors
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Mirror owner.
    /// </summary>
    //  *** Start programmer edit section *** (MirrorOwner CustomAttributes)

    //  *** End programmer edit section *** (MirrorOwner CustomAttributes)
    [AutoAltered()]
    [Caption("Mirror owner")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MirrorOwnerE", new string[] {
            "BuyDate as \'Buy date\'",
            "Person as \'Person\'",
            "Person.Name as \'Name\'"}, Hidden=new string[] {
            "Person.Name"})]
    [MasterViewDefineAttribute("MirrorOwnerE", "Person", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class MirrorOwner : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fBuyDate;
        
        private IIS.Mirrors.Person fPerson;
        
        private IIS.Mirrors.Mirror fMirror;
        
        //  *** Start programmer edit section *** (MirrorOwner CustomMembers)

        //  *** End programmer edit section *** (MirrorOwner CustomMembers)

        
        /// <summary>
        /// BuyDate.
        /// </summary>
        //  *** Start programmer edit section *** (MirrorOwner.BuyDate CustomAttributes)

        //  *** End programmer edit section *** (MirrorOwner.BuyDate CustomAttributes)
        public virtual System.DateTime BuyDate
        {
            get
            {
                //  *** Start programmer edit section *** (MirrorOwner.BuyDate Get start)

                //  *** End programmer edit section *** (MirrorOwner.BuyDate Get start)
                System.DateTime result = this.fBuyDate;
                //  *** Start programmer edit section *** (MirrorOwner.BuyDate Get end)

                //  *** End programmer edit section *** (MirrorOwner.BuyDate Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (MirrorOwner.BuyDate Set start)

                //  *** End programmer edit section *** (MirrorOwner.BuyDate Set start)
                this.fBuyDate = value;
                //  *** Start programmer edit section *** (MirrorOwner.BuyDate Set end)

                //  *** End programmer edit section *** (MirrorOwner.BuyDate Set end)
            }
        }
        
        /// <summary>
        /// Mirror owner.
        /// </summary>
        //  *** Start programmer edit section *** (MirrorOwner.Person CustomAttributes)

        //  *** End programmer edit section *** (MirrorOwner.Person CustomAttributes)
        [NotNull()]
        public virtual IIS.Mirrors.Person Person
        {
            get
            {
                //  *** Start programmer edit section *** (MirrorOwner.Person Get start)

                //  *** End programmer edit section *** (MirrorOwner.Person Get start)
                IIS.Mirrors.Person result = this.fPerson;
                //  *** Start programmer edit section *** (MirrorOwner.Person Get end)

                //  *** End programmer edit section *** (MirrorOwner.Person Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (MirrorOwner.Person Set start)

                //  *** End programmer edit section *** (MirrorOwner.Person Set start)
                this.fPerson = value;
                //  *** Start programmer edit section *** (MirrorOwner.Person Set end)

                //  *** End programmer edit section *** (MirrorOwner.Person Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Mirrors.Mirror.
        /// </summary>
        //  *** Start programmer edit section *** (MirrorOwner.Mirror CustomAttributes)

        //  *** End programmer edit section *** (MirrorOwner.Mirror CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Mirrors.Mirror Mirror
        {
            get
            {
                //  *** Start programmer edit section *** (MirrorOwner.Mirror Get start)

                //  *** End programmer edit section *** (MirrorOwner.Mirror Get start)
                IIS.Mirrors.Mirror result = this.fMirror;
                //  *** Start programmer edit section *** (MirrorOwner.Mirror Get end)

                //  *** End programmer edit section *** (MirrorOwner.Mirror Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (MirrorOwner.Mirror Set start)

                //  *** End programmer edit section *** (MirrorOwner.Mirror Set start)
                this.fMirror = value;
                //  *** Start programmer edit section *** (MirrorOwner.Mirror Set end)

                //  *** End programmer edit section *** (MirrorOwner.Mirror Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MirrorOwnerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MirrorOwnerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MirrorOwnerE", typeof(IIS.Mirrors.MirrorOwner));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of MirrorOwner.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfMirrorOwner CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfMirrorOwner CustomAttributes)
    public class DetailArrayOfMirrorOwner : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Mirrors.DetailArrayOfMirrorOwner members)

        //  *** End programmer edit section *** (IIS.Mirrors.DetailArrayOfMirrorOwner members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type MirrorOwner by index.
        /// </summary>
        /// <summary>
        /// Adds object with type MirrorOwner.
        /// </summary>
        public DetailArrayOfMirrorOwner(IIS.Mirrors.Mirror fMirror) : 
                base(typeof(MirrorOwner), ((ICSSoft.STORMNET.DataObject)(fMirror)))
        {
        }
        
        public IIS.Mirrors.MirrorOwner this[int index]
        {
            get
            {
                return ((IIS.Mirrors.MirrorOwner)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Mirrors.MirrorOwner dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
