//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mirrors
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Mirror type.
    /// </summary>
    // *** Start programmer edit section *** (MirrorType CustomAttributes)

    // *** End programmer edit section *** (MirrorType CustomAttributes)
    [AutoAltered()]
    [Caption("Mirror type")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MirrorTypeE", new string[] {
            "Name as \'Name\'"})]
    [View("MirrorTypeL", new string[] {
            "Name as \'Name\'"})]
    public class MirrorType : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (MirrorType CustomMembers)

        // *** End programmer edit section *** (MirrorType CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (MirrorType.Name CustomAttributes)

        // *** End programmer edit section *** (MirrorType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (MirrorType.Name Get start)

                // *** End programmer edit section *** (MirrorType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (MirrorType.Name Get end)

                // *** End programmer edit section *** (MirrorType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (MirrorType.Name Set start)

                // *** End programmer edit section *** (MirrorType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (MirrorType.Name Set end)

                // *** End programmer edit section *** (MirrorType.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MirrorTypeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MirrorTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MirrorTypeE", typeof(IIS.Mirrors.MirrorType));
                }
            }
            
            /// <summary>
            /// "MirrorTypeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MirrorTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MirrorTypeL", typeof(IIS.Mirrors.MirrorType));
                }
            }
        }
    }
}
